baseURL = "https://digital-land.github.io/"
languageCode = "en-uk"
title = "Digital Land"
theme = "govuk"
googleAnalytics = "UA-127566551-1"
enableRobotsTXT = true

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
  global_header_text = "GOV.UK"
  servicename = "Digital Land"
  users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Team"
  url = "/about"
  currentpage = true

  [[params.propositionlinks]]
  name = "Projects"
  url = "/project/"

  [[params.propositionlinks]]
  name = "Weeknotes"
  url = "/weeknote/"

  [[params.propositionlinks]]
  name = "Blog"
  url = "/blog-post/"

  [[params.propositionlinks]]
  name = "Guidance"
  url = "/guidance/"

  [[params.propositionlinks]]
  name = "Datasets"
  url = "/dataset/"

  [[params.propositionlinks]]
  name = "Organisations"
  url = "/organisation/"

  [[params.propositionlinks]]
  name = "Map"
  url = "/map/"

  [[params.footer_meta_links]]
  name = "Cookies"
  url = "/cookies"

  [[params.footer_meta_links]]
  name = "Accessibility statement"
  url = "/accessibility-statement"

  [[params.guidance_links]]
  name = "Finding the local authority for an address"
  url = "https://digital-land.github.io/local-authority-addresses/"
  summary = "Follow our guidance when you are trying to work out which Local Authority an address is in."

[taxonomies]
  tag = "tags"
  pattern = "patterns"
